"""initial tables

Revision ID: 11d3a0febb88
Revises: 2682c921f2be
Create Date: 2021-08-30 20:45:10.768737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d3a0febb88'
down_revision = '2682c921f2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
