"""update movie

Revision ID: 2e702a5c1b74
Revises: f0b823c48dd6
Create Date: 2021-08-30 20:54:57.811897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e702a5c1b74'
down_revision = 'f0b823c48dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
