"""update movie

Revision ID: 2e94685be538
Revises: 81ea9b31e1ee
Create Date: 2021-08-30 21:02:13.578375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e94685be538'
down_revision = '81ea9b31e1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('year', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'year')
    # ### end Alembic commands ###
