"""initial tables

Revision ID: db45fb8c83fb
Revises: ae2a3de5d20e
Create Date: 2021-08-29 23:24:33.584219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db45fb8c83fb'
down_revision = 'ae2a3de5d20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
