"""initial tables

Revision ID: f0b823c48dd6
Revises: 11d3a0febb88
Create Date: 2021-08-30 20:53:46.641499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b823c48dd6'
down_revision = '11d3a0febb88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
